const wordEntries = [
  {'word': 'common', 'path': 'Vault/common.html'},
  {'word': 'common', 'path': 'Vault/common.html'},
  {'word': 'common', 'path': 'Vault/common.html'},
  {'word': 'common', 'path': 'Vault/common.html'},
  {'word': 'common', 'path': 'Vault/common.html'},
  {'word': 'common', 'path': 'Vault/common.html'},
  {'word': 'common', 'path': 'Vault/common.html'},
  {'word': 'common', 'path': 'Vault/common.html'},
  {'word': 'common', 'path': 'Vault/common.html'},
  {'word': 'common', 'path': 'Vault/common.html'},
  {'word': 'common', 'path': 'Vault/common.html'},
  {'word': 'common', 'path': 'Vault/common.html'},
  {'word': 'debit', 'path': 'Vault/debit.html'},
  {'word': 'balance', 'path': 'Vault/balance.html'},
  {'word': 'account', 'path': 'Vault/account.html'},
  {'word': 'across', 'path': 'Vault/across.html'},
  {'word': 'cross', 'path': 'Vault/cross.html'},
  {'word': 'box', 'path': 'Vault/box.html'},
  {'word': 'content', 'path': 'Vault/content.html'},
  {'word': 'letter', 'path': 'Vault/letter.html'},
  {'word': 'basket', 'path': 'Vault/basket.html'},
  {'word': 'bucket', 'path': 'Vault/bucket.html'},
  {'word': 'container | contain', 'path': 'Vault/container.html'},
  {'word': 'glass', 'path': 'Vault/glass.html'},
  {'word': 'bin | binning', 'path': 'Vault/bin.html'},
  {'word': 'deterrence | deterrent | deter', 'path': 'Vault/deterrence.html'},
  {'word': 'charge', 'path': 'Vault/charge.html'},
  {'word': 'par', 'path': 'Vault/par.html'},
  {'word': 'phony', 'path': 'Vault/phony.html'},
  {'word': 'snake', 'path': 'Vault/snake.html'},
  {'word': 'tablet', 'path': 'Vault/tablet.html'},
  {'word': 'file', 'path': 'Vault/file.html'},
  {'word': 'podcast', 'path': 'Vault/podcast.html'},
  {'word': 'cast', 'path': 'Vault/cast.html'},
  {'word': 'pod', 'path': 'Vault/pod.html'},
  {'word': 'design', 'path': 'Vault/design.html'},
  {'word': 'seldom', 'path': 'Vault/seldom.html'},
  {'word': 'never', 'path': 'Vault/never.html'},
  {'word': 'rare | rarely | rarity', 'path': 'Vault/rare.html'},
  {'word': 'occasion | occasional', 'path': 'Vault/occasion.html'},
  {'word': 'dub', 'path': 'Vault/dub.html'},
  {'word': 'sub', 'path': 'Vault/sub.html'},
  {'word': 'tablature', 'path': 'Vault/tablature.html'},
  {'word': 'table | tabular | tabulate', 'path': 'Vault/table.html'},
  {'word': 'tab', 'path': 'Vault/tab.html'},
  {'word': 'continue | continuity | ', 'path': 'Vault/continue.html'},
  {'word': 'handle | handler | handling', 'path': 'Vault/handle.html'},
  {'word': 'quality', 'path': 'Vault/quality.html'},
  {'word': 'goods | good | goodie | goody | goodish', 'path': 'Vault/goods.html'},
  {'word': 'throw', 'path': 'Vault/throw.html'},
  {'word': 'efficiency | efficient', 'path': 'Vault/efficiency.html'},
  {'word': 'specification', 'path': 'Vault/specification.html'},
  {'word': 'efficient | efficiency', 'path': 'Vault/efficient.html'},
  {'word': 'home', 'path': 'Vault/home.html'},
  {'word': 'flat', 'path': 'Vault/flat.html'},
  {'word': 'house', 'path': 'Vault/house.html'},
  {'word': 'store', 'path': 'Vault/store.html'},
  {'word': 'shop', 'path': 'Vault/shop.html'},
  {'word': 'urban', 'path': 'Vault/urban.html'},
  {'word': 'folk', 'path': 'Vault/folk.html'},
  {'word': 'rural', 'path': 'Vault/rural.html'},
  {'word': 'country', 'path': 'Vault/country.html'},
  {'word': 'village', 'path': 'Vault/village.html'},
  {'word': 'town', 'path': 'Vault/town.html'},
  {'word': 'city', 'path': 'Vault/city.html'},
  {'word': 'orchestra', 'path': 'Vault/ororchestra.html'},
  {'word': 'trade | trader', 'path': 'Vault/trade.html'},
  {'word': 'custom | customer | customs | customary | customize | accustom', 'path': 'Vault/custom.html'},
  {'word': 'generation | generate | generative', 'path': 'Vault/generation.html'},
  {'word': 'product | produce | producer | production | reproduction | productive | reproduce', 'path': 'Vault/product.html'},
  {'word': 'business', 'path': 'Vault/business.html'},
  {'word': 'common', 'path': 'Vault/common.html'},
  {'word': 'practice', 'path': 'Vault/practice.html'},
  {'word': 'craft', 'path': 'Vault/craft.html'},
  {'word': 'art | artist | artistry | artistic | arty', 'path': 'Vault/art.html'},
  {'word': 'describe |  description | descriptive', 'path': 'Vault/describe.html'},
  {'word': 'slope', 'path': 'Vault/slope.html'},
  {'word': 'drop', 'path': 'Vault/drop.html'},
  {'word': 'legend', 'path': 'Vault/legend.html'},
  {'word': 'myth', 'path': 'Vault/myth.html'},
  {'word': 'syn- | sym-', 'path': 'Vault/syn-prefix.html'},
  {'word': 'string', 'path': 'Vault/string.html'},
  {'word': 'harmony', 'path': 'Vault/harmony.html'},
  {'word': 'symphony', 'path': 'Vault/symphony.html'},
  {'word': 'opus', 'path': 'Vault/opus.html'},
  {'word': 'enclose |  enclosure', 'path': 'Vault/enclose.html'},
  {'word': 'pen', 'path': 'Vault/pen.html'},
  {'word': 'humane', 'path': 'Vault/humane.html'},
  {'word': 'static dynamic', 'path': 'Vault/static_dynamic.html'},
  {'word': 'raster', 'path': 'Vault/raster.html'},
  {'word': 'vector', 'path': 'Vault/vector.html'},
  {'word': 'sketch', 'path': 'Vault/sketch.html'},
  {'word': 'cut', 'path': 'Vault/cut.html'},
  {'word': 'group', 'path': 'Vault/group.html'},
  {'word': 'jagged', 'path': 'Vault/jagged.html'},
  {'word': 'score |  scoring |  scorer', 'path': 'Vault/score.html'},
  {'word': 'rate', 'path': 'Vault/rate.html'},
  {'word': 'review', 'path': 'Vault/review.html'},
  {'word': 'amount', 'path': 'Vault/amount.html'},
  {'word': 'around', 'path': 'Vault/around.html'},
  {'word': 'round', 'path': 'Vault/round.html'},
  {'word': 'prince', 'path': 'Vault/prince.html'},
  {'word': 'principal', 'path': 'Vault/principal.html'},
  {'word': 'principle', 'path': 'Vault/principle.html'},
  {'word': 'parkour', 'path': 'Vault/parkour.html'},
  {'word': 'vault', 'path': 'Vault/vault.html'},
  {'word': 'deal |  dealer', 'path': 'Vault/deal.html'},
  {'word': 'sober', 'path': 'Vault/sober.html'},
  {'word': 'pal', 'path': 'Vault/pal.html'},
  {'word': 'routine', 'path': 'Vault/routine.html'},
  {'word': 'route', 'path': 'Vault/route.html'},
  {'word': 'miss |  missing', 'path': 'Vault/miss.html'},
  {'word': 'formula', 'path': 'Vault/formula.html'},
  {'word': 'exchange format', 'path': 'Vault/exchange_format.html'},
  {'word': 'return', 'path': 'Vault/return.html'},
  {'word': 'refund', 'path': 'Vault/refund.html'},
  {'word': 'interchange |  change |  ', 'path': 'Vault/interchange.html'},
  {'word': 'exchange', 'path': 'Vault/exchange.html'},
  {'word': 'pack |  package |  packaging |  packet', 'path': 'Vault/pack.html'},
  {'word': 'utility', 'path': 'Vault/utility.html'},
  {'word': 'electrical |  electrics |  electrician |  electricity |  electrify', 'path': 'Vault/electrical.html'},
  {'word': 'cellar', 'path': 'Vault/cellar.html'},
  {'word': 'coping', 'path': 'Vault/coping.html'},
  {'word': 'mechanical |  machine |  machinery |  mechanics |  mechanism', 'path': 'Vault/mechanical.html'},
  {'word': 'objective', 'path': 'Vault/objective.html'},
  {'word': 'whist', 'path': 'Vault/whist.html'},
  {'word': 'discard', 'path': 'Vault/discard.html'},
  {'word': 'hand', 'path': 'Vault/hand.html'},
  {'word': 'pass', 'path': 'Vault/pass.html'},
  {'word': 'suit', 'path': 'Vault/suit.html'},
  {'word': 'club', 'path': 'Vault/club.html'},
  {'word': 'heart', 'path': 'Vault/heart.html'},
  {'word': 'trick |  tricky |  trickery |  trickster', 'path': 'Vault/trick.html'},
  {'word': 'trump', 'path': 'Vault/trump.html'},
  {'word': 'transcript', 'path': 'Vault/transcript.html'},
  {'word': 'freelance |  freelancer', 'path': 'Vault/freelance.html'},
  {'word': 'supply |  supplier', 'path': 'Vault/supply.html'},
  {'word': 'demand |  demanding', 'path': 'Vault/demand.html'},
  {'word': 'arbitrage', 'path': 'Vault/arbitrage.html'},
  {'word': 'collapse', 'path': 'Vault/collapse.html'},
  {'word': 'tent', 'path': 'Vault/tent.html'},
  {'word': 'camp', 'path': 'Vault/camp.html'},
  {'word': 'recognition |  recognize', 'path': 'Vault/recognition.html'},
  {'word': 'liquid |  liquidity', 'path': 'Vault/liquid.html'},
  {'word': 'money', 'path': 'Vault/money.html'},
  {'word': 'asset', 'path': 'Vault/asset.html'},
  {'word': 'title |  subtitle |  entitle |  titled', 'path': 'Vault/title.html'},
  {'word': 'anatomy', 'path': 'Vault/anatomy.html'},
  {'word': 'query', 'path': 'Vault/query.html'},
  {'word': 'browse |  browser', 'path': 'Vault/browse.html'},
  {'word': 'crawl | crawler | crawling', 'path': 'Vault/crawl.html'},
  {'word': 'essence | essential', 'path': 'Vault/essence.html'},
  {'word': 'work | worker | rework | workaholic | working', 'path': 'Vault/work.html'},
  {'word': 'found', 'path': 'Vault/found.html'},
  {'word': 'select | selection | selector | selective', 'path': 'Vault/select.html'},
  {'word': 'relevant | relevance', 'path': 'Vault/relevant.html'},
  {'word': 'canon | canonical', 'path': 'Vault/canon.html'},
  {'word': 'index', 'path': 'Vault/index.html'},
  {'word': 'cursor', 'path': 'Vault/cursor.html'},
  {'word': 'caret', 'path': 'Vault/caret.html'},
  {'word': 'pointer | point | pointy | pointed', 'path': 'Vault/pointer.html'},
  {'word': 'swipe', 'path': 'Vault/swipe.html'},
  {'word': 'second | secondary', 'path': 'Vault/second.html'},
  {'word': 'issue', 'path': 'Vault/issue.html'},
  {'word': 'case', 'path': 'Vault/case.html'},
  {'word': 'volume', 'path': 'Vault/volume.html'},
  {'word': 'gallon', 'path': 'Vault/gallon.html'},
  {'word': 'pint', 'path': 'Vault/pint.html'},
  {'word': 'cup', 'path': 'Vault/cup.html'},
  {'word': 'quart', 'path': 'Vault/quart.html'},
  {'word': 'script', 'path': 'Vault/script.html'},
  {'word': 'manual', 'path': 'Vault/manual.html'},
  {'word': 'quarter | quarters | quarterly', 'path': 'Vault/quarter.html'},
  {'word': 'window', 'path': 'Vault/window.html'},
  {
    'word': 'arrange | arranged | arrangement | arranger | rearrange',
    'path': 'Vault/arrange.html'
  },
  {'word': 'faction', 'path': 'Vault/faction.html'},
  {'word': 'absent | absence', 'path': 'Vault/absent.html'},
  {
    'word': 'present | presently | presentation | presence',
    'path': 'Vault/present.html'
  },
  {'word': 'rule | ruler | ruling | unruly | overrule', 'path': 'Vault/rule.html'},
  {'word': 'rule of thumb', 'path': 'Vault/rule_of_thumb.html'},
  {'word': 'drone', 'path': 'Vault/drone.html'},
  {'word': 'combat | combatant', 'path': 'Vault/combat.html'},
  {'word': 'strike | striker | striking', 'path': 'Vault/strike.html'},
  {'word': 'agent', 'path': 'Vault/agent.html'},
  {'word': 'deploy | deployment', 'path': 'Vault/deploy.html'},
  {
    'word': 'intelligence | intelligent | intelligentsia',
    'path': 'Vault/intelligence.html'
  },
  {'word': 'agency', 'path': 'Vault/agency.html'},
  {'word': 'nation | national | nationalize', 'path': 'Vault/nation.html'},
  {'word': '-ian | -an', 'path': 'Vault/suffix-ian-an.html'},
  {'word': 'guard | guardian', 'path': 'Vault/guard.html'},
  {'word': 'coast | coastal', 'path': 'Vault/coast.html'},
  {'word': 'beef', 'path': 'Vault/beef.html'},
  {'word': 'wag', 'path': 'Vault/wag.html'},
  {'word': 'navy', 'path': 'Vault/navy.html'},
  {'word': 'marine', 'path': 'Vault/marine.html'},
  {'word': 'army', 'path': 'Vault/army.html'},
  {'word': 'Warrant | Warrant Officer', 'path': 'Vault/warrant.html'},
  {'word': 'corporal', 'path': 'Vault/corporal.html'},
  {'word': 'general | generalist | generalize', 'path': 'Vault/general.html'},
  {'word': 'special | specialist | specialize', 'path': 'Vault/special.html'},
  {'word': 'public', 'path': 'Vault/public.html'},
  {'word': 'private', 'path': 'Vault/private.html'},
  {'word': 'rank', 'path': 'Vault/rank.html'},
  {
    'word': 'weigh | outweigh | overweight | weight | weighty',
    'path': 'Vault/weigh.html'
  },
  {'word': 'friction', 'path': 'Vault/friction.html'},
  {'word': 'gravity | gravitation', 'path': 'Vault/gravity.html'},
  {'word': 'mass', 'path': 'Vault/mass.html'},
  {'word': 'normal | normalize | abnormal | normality', 'path': 'Vault/normal.html'},
  {'word': 'force | forcible | forceful', 'path': 'Vault/force.html'},
  {
    'word':
        'military | militant | militia | militancy | militaristic | militarism | militarist',
    'path': 'Vault/military.html'
  },
  {'word': 'army region', 'path': 'Vault/army_region.html'},
  {'word': 'army group', 'path': 'Vault/army_group.html'},
  {'word': 'field army', 'path': 'Vault/field_army.html'},
  {'word': 'corps', 'path': 'Vault/corps.html'},
  {'word': 'division | divide | subdivide | divisive', 'path': 'Vault/division.html'},
  {'word': 'brigade | brigadier', 'path': 'Vault/brigade.html'},
  {'word': 'colonel', 'path': 'Vault/colonel.html'},
  {'word': 'battalion', 'path': 'Vault/battalion.html'},
  {'word': 'captain', 'path': 'Vault/captain.html'},
  {'word': 'company', 'path': 'Vault/company.html'},
  {'word': 'lieutenant', 'path': 'Vault/lieutenant.html'},
  {'word': 'section | sectional', 'path': 'Vault/section.html'},
  {'word': 'platoon', 'path': 'Vault/platoon.html'},
  {'word': 'squad', 'path': 'Vault/squad.html'},
  {'word': 'sergeant', 'path': 'Vault/sergeant.html'},
  {'word': '-ship', 'path': 'Vault/suffix-ship.html'},
  {'word': 'lead | leader | leading', 'path': 'Vault/lead.html'},
  {'word': 'member', 'path': 'Vault/member.html'},
  {'word': 'team', 'path': 'Vault/team.html'},
  {'word': 'command', 'path': 'Vault/command.html'},
  {'word': 'opt | coopt | option | optional', 'path': 'Vault/option.html'},
  {'word': 'control | controller | controlling', 'path': 'Vault/control.html'},
  {'word': 'tile', 'path': 'Vault/tile.html'},
  {'word': 'half', 'path': 'Vault/half.html'},
  {'word': 'shortcut', 'path': 'Vault/shortcut.html'},
  {'word': 'mission', 'path': 'Vault/mission.html'},
  {
    'word': 'operate | cooperate | operative | operation | operator',
    'path': 'Vault/operate.html'
  },
  {'word': 'install', 'path': 'Vault/install.html'},
  {'word': 'paste', 'path': 'Vault/paste.html'},
  {'word': 'typography', 'path': 'Vault/typography.html'},
  {
    'word': 'type | typology | typical | typological | typify',
    'path': 'Vault/type.html'
  },
  {'word': 'etymon | etymology', 'path': 'Vault/etymology.html'},
  {'word': 'analyze | analysis | analyst | analytical', 'path': 'Vault/analyze.html'},
  {'word': 'perform | performance', 'path': 'Vault/perform.html'},
  {'word': 'item | itemize', 'path': 'Vault/item.html'},
  {'word': 'model', 'path': 'Vault/model.html'},
  {'word': 'age', 'path': 'Vault/age.html'},
  {'word': 'transition', 'path': 'Vault/transition.html'},
  {'word': 'wall', 'path': 'Vault/wall.html'},
  {'word': 'prompt', 'path': 'Vault/prompt.html'},
  {'word': 'Darwin', 'path': 'Vault/Darwin.html'},
  {'word': 'foundation', 'path': 'Vault/foundation.html'},
  {'word': 'furnish | furniture | furnishings', 'path': 'Vault/furnish.html'},
  {'word': 'truncate | truncation', 'path': 'Vault/truncate.html'},
  {'word': '-ery | -ry', 'path': 'Vault/suffix-ery.html'},
  {'word': 'brew', 'path': 'Vault/brew.html'},
  {'word': 'bottle', 'path': 'Vault/bottle.html'},
  {
    'word': 'organize | organization | organizational',
    'path': 'Vault/organize.html'
  },
  {'word': 'manage | manager | management', 'path': 'Vault/manage.html'},
  {'word': 'suite', 'path': 'Vault/suite.html'},
  {'word': 'define | undefined | definite | definition | HD', 'path': 'Vault/define.html'},
  {'word': 'booth', 'path': 'Vault/booth.html'},
  {'word': 'portable', 'path': 'Vault/portable.html'},
  {'word': 'port', 'path': 'Vault/port.html'},
  {'word': 'macintosh | MAC', 'path': 'Vault/macintosh.html'},
  {'word': 'monitor', 'path': 'Vault/monitor.html'},
  {'word': 'toast', 'path': 'Vault/toast.html'},
  {'word': 'initial', 'path': 'Vault/initial.html'},
  {'word': 'evaluate | evaluation', 'path': 'Vault/evaluate.html'},
  {'word': 'suppress', 'path': 'Vault/suppress.html'},
  {
    'word': 'express | expression | expressive | expressively',
    'path': 'Vault/express.html'
  },
  {'word': 'runtime | runtime environment', 'path': 'Vault/runtime.html'},
  {'word': 'format', 'path': 'Vault/format.html'},
  {'word': '-ial', 'path': 'Vault/suffix-ial.html'},
  {'word': 'different | difference | differential', 'path': 'Vault/different.html'},
  {'word': 'state', 'path': 'Vault/state.html'},
  {'word': 'constituent', 'path': 'Vault/constituent.html'},
  {'word': 'affair', 'path': 'Vault/affair.html'},
  {'word': 'federal | federalism', 'path': 'Vault/federal.html'},
  {'word': 'match | matching', 'path': 'Vault/match.html'},
  {'word': 'citric', 'path': 'Vault/citric.html'},
  {'word': 'Tanog', 'path': 'Vault/Tanog.html'},
  {'word': 'Camelot', 'path': 'Vault/Camelot.html'},
  {'word': 'Asgard', 'path': 'Vault/Asgard.html'},
  {'word': 'EI Dorado', 'path': 'Vault/EI_Dorado.html'},
  {'word': 'Avalon', 'path': 'Vault/Avalon.html'},
  {'word': 'Uruk', 'path': 'Vault/Uruk.html'},
  {'word': 'Shambala', 'path': 'Vault/Shambala.html'},
  {'word': 'Atlantis', 'path': 'Vault/Atlantis.html'},
  {'word': 'Buddha', 'path': 'Vault/buddha.html'},
  {'word': 'dragon fruit | pitaya', 'path': 'Vault/pitaya.html'},
  {'word': 'dragon', 'path': 'Vault/dragon.html'},
  {'word': 'fig', 'path': 'Vault/fig.html'},
  {'word': 'date | dates', 'path': 'Vault/date.html'},
  {'word': 'pomegranate', 'path': 'Vault/pomegranate.html'},
  {'word': 'mango', 'path': 'Vault/mango.html'},
  {'word': 'chord', 'path': 'Vault/chord.html'},
  {'word': 'poly-', 'path': 'Vault/poly-prefix.html'},
  {'word': 'medium[media]', 'path': 'Vault/medium.html'},
  {'word': '-eer', 'path': 'Vault/suffix-eer.html'},
  {'word': 'profit | profiteer', 'path': 'Vault/profit.html'},
  {'word': 'expand | expansion | expandable', 'path': 'Vault/expand.html'},
  {'word': 'extend', 'path': 'Vault/extend.html'},
  {'word': 'extent', 'path': 'Vault/extent.html'},
  {'word': 'extensible', 'path': 'Vault/extensible.html'},
  {'word': 'leg', 'path': 'Vault/leg.html'},
  {'word': 'blade', 'path': 'Vault/blade.html'},
  {'word': 'loin', 'path': 'Vault/loin.html'},
  {'word': 'belly', 'path': 'Vault/belly.html'},
  {'word': 'shank', 'path': 'Vault/shank.html'},
  {'word': 'hock', 'path': 'Vault/hock.html'},
  {'word': 'right | rightly', 'path': 'Vault/right.html'},
  {'word': 'monolith | monolithic', 'path': 'Vault/monolith.html'},
  {'word': 'shape', 'path': 'Vault/shape.html'},
  {'word': 'furnace', 'path': 'Vault/furnace.html'},
  {
    'word': 'clear | clarity | clarify | clearance | clarification',
    'path': 'Vault/clear.html'
  },
  {'word': 'way', 'path': 'Vault/way.html'},
  {'word': 'road | Rd.', 'path': 'Vault/road.html'},
  {'word': 'path', 'path': 'Vault/path.html'},
  {'word': 'track', 'path': 'Vault/track.html'},
  {'word': 'unit', 'path': 'Vault/unit.html'},
  {'word': 'minor', 'path': 'Vault/minor.html'},
  {'word': 'major', 'path': 'Vault/major.html'},
  {'word': 'credit', 'path': 'Vault/credit.html'},
  {
    'word': 'graduate | undergraduate | postgraduate',
    'path': 'Vault/graduate.html'
  },
  {'word': 'ME | MTech', 'path': 'Vault/ME_MTech.html'},
  {'word': 'BE | BTech', 'path': 'Vault/BE_BTech.html'},
  {'word': 'MEd', 'path': 'Vault/MEd.html'},
  {'word': 'BEd', 'path': 'Vault/BEd.html'},
  {'word': 'LLM', 'path': 'Vault/LLM.html'},
  {'word': 'LLB', 'path': 'Vault/LLB.html'},
  {'word': 'MBA', 'path': 'Vault/MBA.html'},
  {'word': 'profession | professional', 'path': 'Vault/profession.html'},
  {'word': 'doctor', 'path': 'Vault/doctor.html'},
  {'word': 'MPhil', 'path': 'Vault/MPhil.html'},
  {'word': 'master | mastered | mastery', 'path': 'Vault/master.html'},
  {'word': 'college', 'path': 'Vault/college.html'},
  {'word': 'university', 'path': 'Vault/university.html'},
  {'word': 'bachelor', 'path': 'Vault/bachelor.html'},
  {'word': 'associative', 'path': 'Vault/associative.html'},
  {'word': 'association', 'path': 'Vault/association.html'},
  {'word': 'associate', 'path': 'Vault/associate.html'},
  {'word': 'plan | planner | planned | planning', 'path': 'Vault/plan.html'},
  {'word': 'program | programme | programable', 'path': 'Vault/program.html'},
  {'word': 'apartment', 'path': 'Vault/apartment.html'},
  {'word': 'apart', 'path': 'Vault/apart.html'},
  {'word': 'oriental', 'path': 'Vault/oriental.html'},
  {'word': 'compass', 'path': 'Vault/compass.html'},
  {'word': 'degree', 'path': 'Vault/degree.html'},
  {
    'word': 'orient | orientation | orienteering | oriented | orientate',
    'path': 'Vault/orient.html'
  },
  {'word': 'drift', 'path': 'Vault/drift.html'},
  {'word': 'heading', 'path': 'Vault/heading.html'},
  {'word': 'course', 'path': 'Vault/course.html'},
  {'word': 'phylogeny | phylogenetics', 'path': 'Vault/phylogeny.html'},
  {'word': 'organism', 'path': 'Vault/organism.html'},
  {'word': 'alive', 'path': 'Vault/alive.html'},
  {'word': 'life | lifer | lifeless | lifelike', 'path': 'Vault/life.html'},
  {
    'word': 'live | outlive | relive | lively | living | liveable',
    'path': 'Vault/live.html'
  },
  {'word': 'taxonomy | taxonomic', 'path': 'Vault/taxonomy.html'},
  {'word': 'class', 'path': 'Vault/class.html'},
  {'word': 'gradient', 'path': 'Vault/gradient.html'},
  {'word': 'grade | graded', 'path': 'Vault/grade.html'},
  {'word': 'K-12', 'path': 'Vault/K-12.html'},
  {'word': 'through', 'path': 'Vault/through.html'},
  {'word': 'entry | enter | entrance | entrant', 'path': 'Vault/entry.html'},
  {
    'word':
        'form | formation | reform | reformed | reformation | reformist | transform | transformation | transformer',
    'path': 'Vault/form.html'
  },
  {'word': 'process | processor', 'path': 'Vault/process.html'},
  {'word': 'hostel', 'path': 'Vault/hostel.html'},
  {'word': 'mat', 'path': 'Vault/mat.html'},
  {'word': 'bunk', 'path': 'Vault/bunk.html'},
  {'word': 'wrap | wrapper', 'path': 'Vault/wrap.html'},
  {'word': 'pliers', 'path': 'Vault/pliers.html'},
  {'word': 'gelatin', 'path': 'Vault/gelatin.html'},
  {'word': 'amateur | amateurish', 'path': 'Vault/amateur.html'},
  {'word': 'dough | doughnut | doughy', 'path': 'Vault/dough.html'},
  {'word': 'yolk', 'path': 'Vault/yolk.html'},
  {'word': 'buck', 'path': 'Vault/buck.html'},
  {'word': 'cent', 'path': 'Vault/cent.html'},
  {'word': 'dollar', 'path': 'Vault/dollar.html'},
  {'word': 'bread', 'path': 'Vault/bread.html'},
  {'word': '-en', 'path': 'Vault/suffix-en.html'},
  {'word': 'carb', 'path': 'Vault/carb.html'},
  {'word': 'lodge | lodging', 'path': 'Vault/lodge.html'},
  {'word': 'hash | hashtag | hashish', 'path': 'Vault/hash.html'},
  {'word': 'question', 'path': 'Vault/question.html'},
  {
    'word': 'divide | division | subdivision | divided | divisive | subdivide',
    'path': 'Vault/divide.html'
  },
  {'word': 'multi-', 'path': 'Vault/multi-prefix.html'},
  {'word': 'multiply', 'path': 'Vault/multiply.html'},
  {'word': 'equal', 'path': 'Vault/equal.html'},
  {'word': '-age', 'path': 'Vault/suffix-age.html'},
  {'word': 'percent | percentage', 'path': 'Vault/percent.html'},
  {'word': 'point | pointless', 'path': 'Vault/point.html'},
  {'word': 'dot', 'path': 'Vault/dot.html'},
  {'word': 'minus', 'path': 'Vault/minus.html'},
  {'word': 'plus', 'path': 'Vault/plus.html'},
  {'word': 'wand', 'path': 'Vault/wand.html'},
  {'word': 'board', 'path': 'Vault/board.html'},
  {'word': 'fashion | fashionable | -fashion', 'path': 'Vault/fashion.html'},
  {
    'word': 'comprehend | comprehensive | comprehension',
    'path': 'Vault/comprehend.html'
  },
  {'word': 'phase', 'path': 'Vault/phase.html'},
  {'word': 'mix | mixed | mixture', 'path': 'Vault/mix.html'},
  {'word': 'colloid | colloidal', 'path': 'Vault/colloid.html'},
  {'word': 'scatter', 'path': 'Vault/scatter.html'},
  {'word': 'suspend | suspension', 'path': 'Vault/suspend.html'},
  {
    'word': 'hetero- | homo- | heterogeneous | homogeneous',
    'path': 'Vault/hetero-homo-prefix.html'
  },
  {'word': 'template', 'path': 'Vault/template.html'},
  {'word': '-ary', 'path': 'Vault/suffix-ary.html'},
  {'word': '-al | -ally', 'path': 'Vault/suffix-al.html'},
  {'word': '-s | -\'s | -s\'', 'path': 'Vault/suffix-s.html'},
  {'word': 'element | elemental | elementary', 'path': 'Vault/element.html'},
  {'word': 'compound', 'path': 'Vault/compound.html'},
  {'word': 'material | materially | materialism', 'path': 'Vault/material.html'},
  {'word': 'matter', 'path': 'Vault/matter.html'},
  {'word': 'substance | substantially', 'path': 'Vault/substance.html'},
  {'word': 'budget', 'path': 'Vault/budget.html'},
  {'word': 'pro', 'path': 'Vault/pro.html'},
  {'word': 'alternative', 'path': 'Vault/alternative.html'},
  {'word': 'alternate', 'path': 'Vault/alternate.html'},
  {'word': 'thread', 'path': 'Vault/thread.html'},
  {'word': 'fabric | fabricate | fabrication', 'path': 'Vault/fabric.html'},
  {'word': 'seam', 'path': 'Vault/seam.html'},
  {'word': 'knot', 'path': 'Vault/knot.html'},
  {'word': 'plain', 'path': 'Vault/plain.html'},
  {
    'word': 'depend | dependency | dependent | independent | dependant',
    'path': 'Vault/depend.html'
  },
  {'word': 'stitch', 'path': 'Vault/stitch.html'},
  {'word': '-y', 'path': 'Vault/suffix-y.html'},
  {'word': '-cy', 'path': 'Vault/suffix-cy.html'},
  {'word': '-ency | -ancy', 'path': 'Vault/suffix-ency-ancy.html'},
  {'word': '-ence | -ance', 'path': 'Vault/suffix-ence-ance.html'},
  {'word': 'rely | reliance | reliant | reliable', 'path': 'Vault/rely.html'},
  {'word': 'support', 'path': 'Vault/support.html'},
  {'word': 'leaf[leaves]', 'path': 'Vault/leaf.html'},
  {'word': 'leave[left] | left', 'path': 'Vault/leave.html'},
  {'word': 'rest', 'path': 'Vault/rest.html'},
  {'word': 'grave | gravestone | engrave', 'path': 'Vault/grave.html'},
  {
    'word': 'electrode | cathode | anode | Cathode Ray',
    'path': 'Vault/electrode.html'
  },
  {'word': 'ion | cation | anion | ionic', 'path': 'Vault/ion.html'},
  {'word': '-ion', 'path': 'Vault/suffix-ion.html'},
  {'word': '-ant', 'path': 'Vault/suffix-ant.html'},
  {'word': '-ent', 'path': 'Vault/suffix-ent.html'},
  {'word': 'solve | solvent | solute | solution', 'path': 'Vault/solve.html'},
  {'word': 'avatar', 'path': 'Vault/avatar.html'},
  {'word': '-ism', 'path': 'Vault/suffix-ism.html'},
  {'word': '-ize', 'path': 'Vault/suffix-ize.html'},
  {'word': '-ic', 'path': 'Vault/suffix-ic.html'},
  {'word': 'metaverse', 'path': 'Vault/metaverse.html'},
  {'word': 'meta-', 'path': 'Vault/meta-prefix.html'},
  {'word': 'metamorphic | metamorphism', 'path': 'Vault/metamorphic.html'},
  {'word': 'anthropo-', 'path': 'Vault/anthropo-prefix.html'},
  {
    'word': 'anthropomorphize | anthropomorphic | anthropomorphism',
    'path': 'Vault/anthropomorphism.html'
  },
  {'word': 'anthropology | anthropic', 'path': 'Vault/anthropology.html'},
  {'word': 'morph', 'path': 'Vault/morph.html'},
  {'word': '-ology | -logy', 'path': 'Vault/suffix-ology.html'},
  {'word': '-oid', 'path': 'Vault/suffix-oid.html'},
  {'word': '-ous', 'path': 'Vault/suffix-ous.html'},
  {'word': 'neo-', 'path': 'Vault/neo-prefix.html'},
  {'word': 'studio', 'path': 'Vault/studio.html'},
  {'word': 'study | studious', 'path': 'Vault/study.html'},
  {'word': 'stub', 'path': 'Vault/stub.html'},
  {'word': 'trace', 'path': 'Vault/trace.html'},
];
